PracticeForFriday/Controllers/MagazineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace PracticeForFriday.Controllers
{
	[AllowAnonymous]
    public class MagazineController : Controller
    {
        // GET: Magazine
        
		public ActionResult MagazineView(int? page)
		{
			using (mvcEntities me = new mvcEntities())
			{
				var magaines = me.Magazines.Select(x => x).ToList().ToPagedList(page ?? 1, 5);
				return View(magaines);
			}
				
		}
    }
}

PracticeForFriday/Controllers/RegistrationController.cs
using System.Web.Mvc;
using PracticeForFriday.Models;

namespace PracticeForFriday.Controllers
{
	[RoutePrefix("Create_An_User")]
	[Route("{action=registration}")]
	public class RegistrationController : Controller
    {
        // GET: Registration
		[AllowAnonymous]
        public ActionResult Registration()
        {
            return View();
        }
		[HttpPost]
		[AllowAnonymous]
		public ActionResult Registration(ViewModel vm)
		{
			if (ModelState.IsValid)
			{
				using (mvcEntities me = new mvcEntities())
				{
					Employee emp = new Employee();
					emp.first_name = vm.Employee.first_name;
					emp.last_name = vm.Employee.last_name;
					emp.loginID = vm.Employee.loginID;
					emp.loginPassword = vm.Employee.loginPassword;
					emp.Email_Address = vm.Employee.Email_Address;
					emp.Home_Address = vm.Employee.Home_Address;
					emp.Phone = vm.Employee.Phone;
					me.Employees.Add(emp);
					me.SaveChanges();
					return RedirectToAction("Login","SignIn");
				}
			}
			else {
				return View(vm);
			}
		}
	}
}

PracticeForFriday/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PracticeForFriday/Views/Shared/_practiceLayout.cshtml
<html>
<head>
	<title>
		partice
	</title>
	@Styles.Render("~/Content/css")
	@Styles.Render("~/Content/materialcss")
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/angularjs")
	@Scripts.Render("~/bundles/angularAria")
	@Scripts.Render("~/bundles/angularAnim")
	@Scripts.Render("~/bundles/angularMaterial")
	<style>
		.dropbtn {
			color: white;
			width: 40px;
			height: 40px;
			border: 1px;
			border-radius: 25px;
			cursor: pointer;
		}

		.dropdown {
			position: relative;
			display: inline-block;
		}

		.dropdown-content {
			display: none;
			position: absolute;
			background-color: #f9f9f9;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			z-index: 1;
		}

			.dropdown-content li {
				color: black;
				padding: 12px 16px;
				text-decoration: none;
				display: block;
			}

				.dropdown-content li:hover {
					background-color: #f1f1f1
				}

		.dropdown:hover .dropdown-content {
			display: block;
		}

		.dropdown:hover .dropbtn {
			background-color: #3e8e41;
		}
	</style>
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
		<div class="container topnav">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand topnav" href="#">Practice</a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li>
						@Html.ActionLink("Home", "MagazineView", "Magazine")
					</li>
					@if (!User.Identity.IsAuthenticated)
					{
						<li>
							@Html.ActionLink("Login", "Login", "Project")
						</li>
						<li>
							@Html.ActionLink("Create A new Account", "Registration", "Registration")
						</li>
						<li><img src="~/Images/user.jpg" class="dropbtn" /></li>
					}
					else
					{
						<li>@Html.ActionLink("Top Secret", "content", "Secret")</li>
						if (Session["imgUrl"] != null)
						{
							@Html.Partial("~/Views/Shared/_profilePartial.cshtml");
						}
						else
						{
							<li><img src="~/Images/user.jpg" class="dropbtn" /></li>
						}
						<li>@Html.ActionLink("Logout", "logout", "Secret")</li>
					}

				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</div>
	<div class="container"style="margin-top: 52px">
		@RenderBody()
	</div>
</body>
</html>

PracticeForFriday/Views/Shared/_profilePartial.cshtml
@using PracticeForFriday.Models
@{
	mvcEntities me = new mvcEntities();
	int userid = Convert.ToInt32(Session["ID"]);
	Employee emp = me.Employees.Where(X=>X.userid == userid).First();
	ViewModel vm = new ViewModel();
	vm.Employee = AutoMapper.Mapper.Map<Employee,EmployeeViewModel>(emp);
	
}
	<li>
	<div class="dropdown">
		<img src="@Session["imgUrl"].ToString()" class="dropbtn" />
		<div class="dropdown-content">
			<ol>
				<li>@vm.Employee.first_name</li>
				<li>@vm.Employee.last_name</li>
				<li>3</li>
			</ol>
		</div>
	</div>
</li>

PracticeForFriday/Views/Shared/subScripe.cshtml
@model PracticeForFriday.Models.ViewModel
@using PagedList;
@using PagedList.Mvc;
@{
	List<SelectListItem> mag = new List<SelectListItem>();
	
	List<Magazine> m = (List<Magazine>)TempData["mags"];
	m = (List<Magazine>)Session["magazines"];
	foreach (var item in m)
	{
		SelectListItem li = new SelectListItem();
		li.Value = item.Magazine_ID.ToString();
		li.Text = item.Magazine_Name.ToString();
		mag.Add(li);
	}
	ViewBag.magazines = mag;
}
@using (Html.BeginForm("Create","Content",FormMethod.Post))
{
    @Html.AntiForgeryToken()
   
    <div class="form-horizontal">
        <h4>Subscription</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" hidden>
            @Html.LabelFor(Model => Model.Subscription.SubscriptionID, htmlAttributes: new { @class = "control-label col-md-2" })
        </div>

        <div class="form-group">
            @Html.Label("Magazine Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.DropDownListFor(Model => Model.Subscription.Magazine_ID,(IEnumerable<SelectListItem>)ViewBag.magazines, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.Subscription.Start_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.Subscription.Start_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.Subscription.Start_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.Subscription.End_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.Subscription.End_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.Subscription.End_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.Subscription.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.Subscription.Active, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.Subscription.Active, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(Model => Model.Subscription.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.Subscription.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(Model => Model.Subscription.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(Model => Model.Subscription.User_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.Subscription.User_ID, new { htmlAttributes = new { @class = "form-control", required = "disable" } })
                @Html.ValidationMessageFor(Model => Model.Subscription.User_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}